version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "tokenizin-agency"
    # Add labels
    labels:
      - "dependencies"
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Group all updates together
    groups:
      dependencies:
        patterns:
          - "*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Add labels
    labels:
      - "ci"
      - "dependencies"
    # Group all updates together
    groups:
      actions:
        patterns:
          - "*" 